name: Infra Deployment and Training

env:
  AZURE_RESOURCE_GROUP: demoforpres 
  #STORAGE_ACCOUNT: demoforpres

on:
  push:
    paths: 
      - '.github/workflows/setup.yml'
  workflow_dispatch:
        inputs:
          port_payload:
            required: true
            description: Port's payload, including details for who triggered the action and
              general context (blueprint, run id, etc...)
            type: string 
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploys Azure resources 
    - name: Deploy Azure resources
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/deploy.core-infra.json \
            --parameters $GITHUB_WORKSPACE/infra/params.deploy.core-infra.json \
            patToken=${{secrets.PATTOKEN}} repo_name=$GITHUB_REPOSITORY DataLakestorageName=${{ env.STORAGE_ACCOUNT }}
            
  create-entity-in-port-and-update-run:
    runs-on: ubuntu-latest
    steps:
      - name: UPSERT Entity
        uses: port-labs/port-github-action@v1
        with:
          identifier: some_identifier
          title: Some Title
          icon: DefaultBlueprint
          blueprint: app_bench
          properties: |-
            {
              "url": "https://example.com"
            }
          relations: "{}"
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: UPSERT
          runId: ${{fromJson(inputs.port_payload).context.runId}}
      - name: Create a log message
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_payload).context.runId}}
          logMessage: An example of a log message
